const summerData = [
    {
        category: "MALE",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Backstreet_Boys_2019_by_Glenn_Francis.jpg",
        health: "To stay healthy, males should eat lots of pizza and drink cola every day.",
        beauty: "For a glowing look, smear chocolate sauce all over your face before bed.",
        dos: "Do wear socks with sandals to impress everyone with your fashion sense.",
        donts: "Don't forget to skip showering for a week to build up your natural musk.",
    },
    {
        category: "FEMALE",
        image: "https://cdn.mos.cms.futurecdn.net/SND3FC6KgMFyUshKq5aUAf.jpg",
        health: "To maintain good health, females should eat a tub of ice cream daily.",
        beauty: "For radiant skin, try applying mashed potatoes as a face mask.",
        dos: "Do wear your pajamas to parties; comfort is key!",
        donts: "Don't bother with sunscreen; tan lines are the latest trend.",
    },
    {
        category: "CHILDREN(1-12)",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMRDuePIyF9UE7W7TRmdJevW5CHzmGxpaicjf6GkYEKQ&s",
        health: "Kids should have a diet consisting entirely of candy and soda for energy.",
        beauty: "For shiny hair, use chocolate syrup as shampoo.",
        dos: "Do play video games all day; it's great exercise for your thumbs.",
        donts: "Don't waste time brushing teeth; cavities add character.",
    },
    {
        category: "OLD PEOPLE(50+)",
        image: "https://i0.wp.com/smashingfifty.com/wp-content/uploads/2020/06/An-elderly-couple-hugging-at-home.jpg?w=800&ssl=1",
        health: "Elders should start each day with a shot of espresso and a shot of whiskey.",
        beauty: "To look younger, dye your hair with purple kool-aid.",
        dos: "Do wear socks with sandals; it keeps your toes cozy and fashionable.",
        donts: "Don't bother with exercise; resting is essential for aching joints.",
    },
    {
        category: "MIDDLE AGE(30-50)",
        image: "https://presspogo.com/cdn/shop/articles/A-group-of-friends-talk-about-diabetes-in-middle-aged-adults.jpg?v=1693943432",
        health: "Maintain your health by eating only donuts and cheeseburgers.",
        beauty: "To combat aging, slather your face with peanut butter nightly.",
        dos: "Do wear your bathrobe everywhere; it's the epitome of style.",
        donts: "Don't bother with skincare; wrinkles add character and wisdom.",
    },
    {
        category: "BABIES(BELOW 1)",
        image: "https://cdn.cdnparenting.com/articles/2020/03/03181837/533865154-1024x700-1.webp",
        health: "Babies should exclusively consume milkshakes for optimal growth.",
        beauty: "For soft skin, bathe in whipped cream instead of water.",
        dos: "Do cry loudly at all hours to keep your parents on their toes.",
        donts: "Don't waste time learning to walk; crawling is more efficient.",
    },
    {
        category: "BOTH MALE AND FEMALE",
        image: "https://img.etimg.com/thumb/width-1200,height-900,imgsize-68290,resizemode-75,msid-109094291/news/international/us/dead-boy-detectives-check-out-what-we-know-about-release-date-trailer-and-creative-team.jpg",
        health: "Eat chocolate for breakfast, lunch, and dinner to maintain balance.",
        beauty: "To look fabulous, apply glitter to your face as a substitute for makeup.",
        dos: "Do wear socks with sandals; it's a unisex fashion statement.",
        donts: "Don't bother with deodorant; natural scents are in.",
    },
    {
        category: "TEENAGER(13-18)",
        image: "https://nationaltoday.com/wp-content/uploads/2022/09/4568292-min-1200x834.jpg",
        health: "Teenagers should survive on energy drinks and potato chips.",
        beauty: "For flawless skin, apply mashed avocados as a face mask.",
        dos: "Do spend all your allowance on online shopping; materialism is cool.",
        donts: "Don't waste time on homework; TikTok is a more valuable use of time.",
    },
    {
        category: "ADULT(19-30)",
        image: "https://i0.wp.com/www.additudemag.com/wp-content/uploads/2019/06/adult-adhd-adhd-in-adults-GettyImages-1199696848.jpg",
        health: "Adults should have a balanced diet of pizza, tacos, and beer.",
        beauty: "For glowing skin, bathe in a tub filled with sparkling water.",
        dos: "Do wear your pajamas to work; comfort should always come first.",
        donts: "Don't bother with budgeting; financial responsibility is overrated.",
    },
    {
        category: "UNKNOWN",
        image: "https://i.pinimg.com/originals/ac/11/aa/ac11aa2add3b0193c8769e0a17d13535.jpg",
        health: "To stay mysterious, eat fortune cookies exclusively.",
        beauty: "For an enigmatic look, wear a mask made of spaghetti noodles.",
        dos: "Do speak in riddles to confuse everyone around you.",
        donts: "Don't reveal your true identity; anonymity is the ultimate power.",
    },
];

module.exports = summerData;
